dist: trusty
sudo: required
env:
  matrix:
    - ARCH=x86_64
    - ARCH=armhf
install:
  - sudo .travis/install-alpine
  - sudo .travis/setup-alpine
script: |
  source .travis/common.sh
  alpine_run $USER .travis/build-pkgs
notifications:
  email: false
