dist: trusty
sudo: required
env:
  matrix:
    - ARCH=armhf
install:
  - sudo .travis/alpine-chroot-install -a $ARCH -d /alpine -p build-base 
script: |
  source .travis/common.sh
  alpine_run $USER .travis/build-pkgs
notifications:
  email: false
